/* Copyright 2017 Sven van der Meer <vdmeer.sven@mykolab.com\>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.vandermeer.skb.interfaces.translators.character;

import org.apache.commons.lang3.StringUtils;

import de.vandermeer.skb.interfaces.translators.CharacterTranslator;

/**
 * Translator for plain text characters to AsciiDoc.
 *
 * @author     Sven van der Meer &lt;vdmeer.sven@mykolab.com&gt; - auto-generated by SKB Datatool from SKB CharacterMap data
 * @version    v0.0.2 build 170404 (04-Apr-17) for Java 1.8
 * @since      v0.0.3
 */
public interface Text2AsciiDoc extends CharacterTranslator {

	/**
	 * Creates a new text to ASCIIDOC character translator.
	 * @return new translator
	 */
	static Text2AsciiDoc create(){
		return new Text2AsciiDoc() {
		};
	}

	/** Array of source strings. */
	static final String[] SOURCE_ARRAY = new String[]{
	};

	/** Array of target strings. */
	static final String[] TARGET_ARRAY = new String[]{
	};

	@Override
	default String translateCharacters(String input){
		return StringUtils.replaceEach(input, SOURCE_ARRAY, TARGET_ARRAY);
	}
}
